name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  pipeline:

    runs-on: ubuntu-latest

    steps:

    - name: Descargar código
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: pip install -r requirements.txt

    - name: Ejecutar pruebas
      run: pytest

    - name: Build del proyecto
      run: python -m compileall .

    - name: Simular despliegue
      run: echo "Deploy realizado correctamente"
